site_name: Guía para el rediseno de sistemas web para proveer accesibilidad a usuarios con ceguera total.
site_description: Guía para rediseñar sistemas web para dar accesibilidad a usuarios con ceguera total.
theme:
  name: material
  language: es  # Muy importante para que los lectores de pantalla sepan el idioma
  features:
    - navigation.sections
    - navigation.expand

nav:
  - Inicio: index.md
  - Fases de la Guía: guideDescription.md
      - Capacitación: fase1.md  # Ajusta los nombres a tus archivos reales
      - Exploración Inicial: fase2.md
      - Evaluación: fase3.md
      - Análisis de Requisitos: fase4.md
      - Recodificación: fase5.md
  - Resultados: resultados.md
  - Conclusiones: final.md
  - Referencias: referencias.md
